services:
  # CalculationService
  pricecalculator:
    build:
      context: ./src/PriceCalculator
    image: ghcr.io/${IMAGE_NAME}/cmlpc:latest
    ports:
      - "2000:80"

  # NGINX API Gateway
  nginx:
    image: nginx:alpine-slim
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pricecalculator