services:
  # CalculationService
  pricecalculator:
    build:
      context: ./src/PriceCalculator
    volumes:
      - shared-config:/app/config

  # NGINX API Gateway
  nginx:
    build:
      context: ./src/nginx
    ports:
      - "8080:80"
    depends_on:
      - pricecalculator
      - admin

  # OSRM (Open Source Routing Machine)
  osrm:
    image: ghcr.io/marekvonrogall/cmlpc/cmlosrm:latest

  # Admin Panel
  admin:
    build:
      context: ./src/Admin
    depends_on:
      - pricecalculator
    volumes:
      - shared-config:/app/config
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}

volumes:
  shared-config:
