services:

  # CalculationService
  pricecalculator:
    build:
      context: ./src/PriceCalculator
    #image: ghcr.io/marekvonrogall/cmlpc/cmlpc:latest
    ports:
      - "8081:80"
    volumes:
      - shared-config:/app/config

  # NGINX API Gateway
  nginx:
    build:
      context: ./src/nginx
    #image: ghcr.io/marekvonrogall/cmlpc/cmlnginx:latest
    ports:
      - "8080:80"
    depends_on:
      - pricecalculator
      - admin

  # OSRM (Open Source Routing Machine)
  osrm:
    image: ghcr.io/marekvonrogall/cmlpc/cmlosrm:latest
    ports:
      - "8082:5000"

  # Admin Panel
  admin:
    build:
     context: ./src/Admin
    #image: ghcr.io/marekvonrogall/cmlpc/cmladmin:latest
    ports:
      - "8083:8083"
    depends_on:
      - pricecalculator
    volumes:
      - shared-config:/app/config
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}

volumes:
  shared-config:
