services:

  # CalculationService
  pricecalculator:
    build:
      context: ./src/PriceCalculator
    image: ghcr.io/${IMAGE_NAME}/cmlpc:latest
    ports:
      - "8081:80"
    volumes:
      - shared-config:/app/config

  # NGINX API Gateway
  nginx:
    build:
      context: ./src/nginx
    image: ghcr.io/${IMAGE_NAME}/cmlnginx:latest
    ports:
      - "8080:80"
    depends_on:
      - pricecalculator
      - admin

  # OSRM (Open Source Routing Machine)
  osrm:
    build:
      context: ./src/OSRM
    image: ghcr.io/${IMAGE_NAME}/cmlosrm:latest
    ports:
      - "8082:5000"

  # ADMIN PANEL
  admin:
    build:
      context: ./src/Admin
    image: ghcr.io/${IMAGE_NAME}/cmladmin:latest
    ports:
      - "8083:8083"
    depends_on:
      - pricecalculator
    volumes:
      - shared-config:/app/config
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}

volumes:
  shared-config:
