services:

  # CalculationService
  pricecalculator:
    build:
      context: ./src/PriceCalculator
    image: ghcr.io/${IMAGE_NAME}/cmlpc:latest
    ports:
      - "8081:80"

  # NGINX API Gateway
  nginx:
    build:
      context: ./src/nginx
    image: ghcr.io/${IMAGE_NAME}/cmlnginx:latest
    ports:
      - "8080:80"
    depends_on:
      - pricecalculator

  # OSRM (Open Source Routing Machine)
  osrm:
    build:
      context: ./src/OSRM
    image: ghcr.io/${IMAGE_NAME}/cmlosrm:latest
    ports:
    - "8082:5000"
