FROM osrm/osrm-backend:latest

# DOWNLOAD MAP DATA FROM https://download.geofabrik.de/europe/germany-latest.osm.pbf INSTEAD OF COPY FROM LOCAL DIR
# COPY ./map_data/germany-latest.osm.pbf /data/germany-latest.osm.pbf
# => EXTRACT AND LOAD MAP

WORKDIR /data
